env = Environment(CCFLAGS='-O0 -g -Wall -Wextra',
                  CPPPATH=['./'])
base_src = [
    'base/time.cpp'
]
env.Library('base', base_src)
env.Program('sieve_test', ['sieve/sieve_test.cpp'], LIBS=['base'], LIBPATH=['.'])
